
name: Swift

on:

  push:
    branches:
      - developer
  pull_request:
    branches:
      - developer
jobs:
  Run:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.2.app && /usr/bin/xcodebuild -version
    - name: re-pod
      run: pod install
    - name: Build app
      run: |
          cd ios && xcodebuild archive \
            -workspace Routes.xcworkspace \
            -scheme Routes \
            -sdk iphoneos14.2 \
            -configuration Release \
            -archivePath $PWD/build/Routes.xcarchive \
            IPHONEOS_DEPLOYMENT_TARGET=9.0
            PROVISIONING_PROFILE="39de84cb-64e2-49fe-9028-461dea17ab3f"
