
name: Swift

on:

  push:
    branches:
      - developer
  pull_request:
    branches:
      - developer
jobs:
  Run:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.2.app && /usr/bin/xcodebuild -version
    - name: re-pod
      run: pod install
    - name: Build and test
      run: |
          xcodebuild clean test -project Routes.xcodeproj -scheme Routes -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
          bash <(curl -s https://codecov.io/bash)
